@ echo off
cls
echo TIME: %TIME% 
echo DATE : %DATE% 
echo OS: %os% 
echo COMPUTERNAME:: %computername% 
echo USERDOMAIN:: %USERDOMAIN%
echo USERNAME:: %USERNAME%
echo USERPROFILE:: %USERPROFILE%
echo USERPROFILE:: %ALLUSERSPROFILE% 


echo WINDIR:: %WINDIR%
echo SYSTEMROOT:: %SYSTEMROOT%
echo SYSTEMDRIVE:: %SYSTEMDRIVE%
echo HOMEDRIVE:: %HOMEDRIVE% 
echo HOMEPATH:: %HOMEPATH% 
echo HOMESHARE:: %HOMESHARE%
echo APPDATA:: %APPDATA% 
echo CURRENTDIR:: %CD% 
echo CMDCMDLINE:: %CMDCMDLINE%
echo CMDEXTVERSION:: %CMDEXTVERSION%
echo COMSPEC:: %COMSPEC% 
echo ERRORLEVEL: %ERRORLEVEL% 
echo PATH %PATH%
echo PATHEXT %PATHEXT%
echo LOGONSVR: %LOGONSEVER%
echo NUMBER_OF_PROCESSORS: %NUMBER_OF_PROCESSORS% 
echo PROCESSOR_ARCHITECTURE: %PROCESSOR_ARCHITECTURE%
echo PROCESSOR_IDENTFIER %PROCESSOR_IDENTFIER%
echo PROCESSOR_LEVEL  %PROCESSOR_LEVEL% 
echo PROCESSOR_REVISION %PROCESSOR_REVISION%
echo PROMPT: %PROMPT%
echo TEMP: %TEMP%
echo TMP: %TMP%
